USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS TEST_DB;

USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

SELECT
    CURRENT_USER() AS USERNAME,
    CURRENT_ROLE() AS ROLE_NAME,
    CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
    CURRENT_DATABASE() AS DATABASE_NAME,
    CURRENT_SCHEMA() AS SCHEMA_NAME;
